version: '3.8'

services:
  db:
    image: mysql:8.0.41
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: xiexie
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

    networks:
      - app-network

  app:
    build: .
    container_name: forum-k
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456789
      - DB_NAME=xiexie
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
